---
# Descr : These are ORC checks for verifying whether Tomcat installation was clean or not
# Date  : 29-07-2016
# Author: Robinson Vijaya Panicker ( E3025574 )

 - set_fact: toolname="Tomcat" software_install=0 software_running=0 software_comm=0 result=0

 - name: Verify tomcat installation path
   command: ls /usr/share/tomcat{{ RHEL_Tomcat.tomcat_version }}
   ignore_errors: yes
   register: isTomcatInstalled

 - debug: var=isTomcatInstalled 

 - set_fact: software_install=1
   when: isTomcatInstalled.stderr.find('No such file or directory') < 0

 - debug: var=software_install

 - name: Verify version of installed tomcat for confirmation
   command: /usr/share/tomcat8/bin/version.sh
   ignore_errors: yes
   register: getTomcatVersion
   when: (software_install|int) and (isTomcatInstalled.stderr.find('No such file or directory') < 0)

# - debug: var=getTomcatVersion

 - name: Verify whether Tomcat is running
   shell: ps -ef | grep tomcat
   register: getTomcatDetails

# - debug: var=getTomcatDetails

 - debug: msg="No Tomcat process running"
   when: (software_install|int == 0) and (getTomcatDetails.stdout.find('/usr/share/tomcat{{RHEL_Tomcat.tomcat_version }}') < 0)

 - set_fact: software_running=1
   when: (software_install|int) and (getTomcatDetails.stdout.find('/usr/share/tomcat{{RHEL_Tomcat.tomcat_version }}') > 0) 

 - command: ls /usr/share/tomcat{{RHEL_Tomcat.tomcat_version }}/webapps/examples
   ignore_errors: yes
   register: ifPath

# - debug: var=ifPath

 - file: path={{ LOCAL_TOMCAT_PATH }}/webapps/examples/ state=directory mode=0755
   when: (software_install|int) and (ifPath.stderr.find('No such file or directory') > 0)

 - command: ls /usr/share/tomcat{{RHEL_Tomcat.tomcat_version }}/webapps/examples
   ignore_errors: yes
   register: ifPath

# - debug: var=ifPath
  
 - name: copy template to test URL
   template: src={{ LOCAL_HTML_PATH  }}.j2 dest={{ LOCAL_TOMCAT_PATH }}/webapps/examples/{{ LOCAL_HTML_PATH  }} owner=root group=root mode=0644
   when: (software_install|int) and (ifPath.stderr.find('No such file or directory') < 0)

 - wait_for: port={{ RHEL_Tomcat. http_port }} delay=20 state=started timeout=120
   ignore_errors: yes
   when: software_install|int

 - name: Verify Tomcat url is accessible from node
   local_action: uri url=http://{{ host_IP }}:{{ RHEL_Tomcat. http_port }}/examples/{{ LOCAL_HTML_PATH  }}
   ignore_errors: yes
   register: urlStatus

# - debug: var=urlStatus

 - set_fact: software_comm=1
   when: (software_install|int) and (urlStatus.status == 200)
 
 - debug: msg="Tomcat url http://{{ host_IP }}:{{ RHEL_Tomcat. http_port }} is not accessible"
   when: (software_install|int) and (urlStatus.status != 200)
 
 - debug: var=software_install
 - debug: var=software_running
 - debug: var=software_comm

 - name: Decide whether all tests have passed
   set_fact: result=1
   when: (software_install | int ) and (software_running | int ) and (software_comm | int )

 - debug: var=result

 - name: update log
   local_action: "shell echo {{ toolname }},{{ result }} >> {{ my_csv_file }}"
